remote_id = ''
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]

[ui_flutter]
peer-sorting = 'Remote ID'
wm_Main = '{"width":800.0,"height":600.0,"offsetWidth":481.0,"offsetHeight":170.0,"isMaximized":true,"isFullscreen":true}'